### ISSUE TITLE
open from opera mini

### ISSUE THREAD

**Issue by mzaini30** [nikitavoloboev/learn-anything#1061] opened 2017-06-13 08:32 UTC
can i access it from opera mini?

**Comment by nikitavoloboev** [comment] 2017-06-13 08:34
I don't have opera mini to test it so not sure. Have you tried it and it doesn't work

**Comment by mzaini30** [comment] 2017-06-13 08:59
i've open it in my galaxy young (opera mini browser). i just get input text without submit button

**Comment by nikitavoloboev** [comment] 2017-06-13 09:00
Sorry about this, I think we know what the issue is. Will be fixed in next update. 🎊

**Comment by Katamori** [comment] 2017-06-13 11:41
Oh yes, browsers without or with limited JS functionality may not display the site properly.

Tried on an acient version of Opera Mobile (12.10), same error. At least here I get the suggestion menu, but selecting any from it has no effect.

**Comment by mzaini30** [comment] 2017-06-13 13:35
thanks friend

**Comment by Katamori** [comment] 2017-06-13 13:58
This issue is going to come a long way, though; ancient browsers are rarely if ever suitable for such one-page applications.

**Closed** 2017-06-13 16:27 UTC
